name: Update GitHub Trending

# 此工作流会在以下情况触发:
# 1. 每天中午 12:00 UTC 时间自动运行
# 2. 当有推送到 main 或 master 分支时
# 3. 手动触发

on:
  push:
    branches: [ main, master ]
  schedule:
    # 每天中午 12:00 UTC 时间运行
    - cron: '0 12 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  update-trending:
    runs-on: ubuntu-latest
    
    # 添加写入权限
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        # 获取所有历史记录，以便正确处理 git 操作
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run scraper
      run: python scraper.py
      
    - name: Commit and push if changed
      run: |
        # 如果您 fork 了此仓库，请修改以下 git 配置为您自己的邮箱和用户名
        # ${GITHUB_ACTOR} 会自动替换为当前 GitHub 用户名
        # 您也可以直接设置为固定值，例如：
        # git config --global user.email "your-email@example.com"
        # git config --global user.name "Your Name"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "${GITHUB_ACTOR}"
        git add -A
        timestamp=$(date -u)
        git commit -m "Update trending repositories: ${timestamp}" || exit 0
        
        # 使用 GITHUB_TOKEN 进行推送，该令牌已被授予写入权限
        git push 